# Generated by Django 3.1.3 on 2020-11-03 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_code', models.CharField(max_length=30)),
                ('bank_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_code', models.CharField(max_length=30)),
                ('account_name', models.CharField(max_length=50)),
                ('account_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_code', models.CharField(max_length=30)),
                ('category_name', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_code', models.CharField(max_length=3)),
                ('currency_name', models.CharField(max_length=150)),
                ('precision', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Payway',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revenue_date', models.DateField()),
                ('trx_title', models.CharField(max_length=150)),
                ('trx_amount', models.FloatField()),
                ('amount', models.FloatField()),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenue_user', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounted_revenue_currency', to='financial.currency')),
                ('payway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenue_payway', to='financial.payway')),
                ('transaction_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenue_category', to='financial.category')),
                ('trx_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenue_currency', to='financial.currency')),
            ],
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_name', models.CharField(max_length=150)),
                ('currency_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_currency', to='financial.currency')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_date', models.DateField()),
                ('trx_title', models.CharField(max_length=150)),
                ('trx_amount', models.FloatField()),
                ('amount', models.FloatField()),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_user', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounted_expense_currency', to='financial.currency')),
                ('payway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_payway', to='financial.payway')),
                ('transaction_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_category', to='financial.category')),
                ('trx_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_currency', to='financial.currency')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(max_length=2)),
                ('numeric_code', models.CharField(max_length=3)),
                ('country_name', models.CharField(max_length=50)),
                ('official_state_name', models.CharField(max_length=150)),
                ('legal_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_currency', to='financial.currency')),
            ],
        ),
        migrations.CreateModel(
            name='BankBranch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_code', models.CharField(max_length=30)),
                ('branch_name', models.CharField(max_length=50)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank', to='financial.bank')),
            ],
        ),
        migrations.CreateModel(
            name='BankBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_balance_account', to='financial.bankaccount')),
                ('currency_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_balance_currency', to='financial.currency')),
            ],
        ),
        migrations.CreateModel(
            name='BankAccountTrx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trx_date', models.DateField(auto_now_add=True)),
                ('trx_title', models.CharField(max_length=50)),
                ('amount', models.FloatField()),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acct_trx_account', to='financial.bankaccount')),
            ],
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_branch', to='financial.bankbranch'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='currency_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_account_currency', to='financial.currency'),
        ),
        migrations.AddField(
            model_name='bank',
            name='bank_country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_country', to='financial.country'),
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_month', models.CharField(max_length=7)),
                ('ent_amount', models.FloatField()),
                ('amount', models.FloatField()),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_currency', to='financial.category')),
                ('ent_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_currency', to='financial.currency')),
                ('trx_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_category', to='financial.category')),
            ],
        ),
    ]
